
package com.ws.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-05-07T11:46:52.186+05:30
 * Generated source version: 2.7.18
 */

@WebFault(name = "AccessDeniedException", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
public class AccessDeniedException_Exception extends Exception {
    
    private com.ws.stub.AccessDeniedException accessDeniedException;

    public AccessDeniedException_Exception() {
        super();
    }
    
    public AccessDeniedException_Exception(String message) {
        super(message);
    }
    
    public AccessDeniedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AccessDeniedException_Exception(String message, com.ws.stub.AccessDeniedException accessDeniedException) {
        super(message);
        this.accessDeniedException = accessDeniedException;
    }

    public AccessDeniedException_Exception(String message, com.ws.stub.AccessDeniedException accessDeniedException, Throwable cause) {
        super(message, cause);
        this.accessDeniedException = accessDeniedException;
    }

    public com.ws.stub.AccessDeniedException getFaultInfo() {
        return this.accessDeniedException;
    }
}
