
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ws.stub;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-05-07T11:46:52.201+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "ExternalReportWSSService",
                      portName = "ExternalReportWSSService",
                      targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService",
                      wsdlLocation = "https://egzv-test.fs.em2.oraclecloud.com/xmlpserver/services/ExternalReportWSSService?wsdl",
                      endpointInterface = "com.ws.stub.ExternalReportWSSService")
                      
public class ExternalReportWSSServiceImpl implements ExternalReportWSSService {

    private static final Logger LOG = Logger.getLogger(ExternalReportWSSServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#updateTemplateForReport(java.lang.String  reportAbsolutePath ,)java.lang.String  templateName ,)java.lang.String  locale ,)byte[]  templateData )*
     */
    public boolean updateTemplateForReport(java.lang.String reportAbsolutePath,java.lang.String templateName,java.lang.String locale,byte[] templateData) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation updateTemplateForReport");
        System.out.println(reportAbsolutePath);
        System.out.println(templateName);
        System.out.println(locale);
        System.out.println(templateData);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#getReportSampleData(java.lang.String  reportAbsolutePath )*
     */
    public byte[] getReportSampleData(java.lang.String reportAbsolutePath) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation getReportSampleData");
        System.out.println(reportAbsolutePath);
        try {
            byte[] _return = new byte[0];
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#uploadReportObject(java.lang.String  reportObjectAbsolutePathURL ,)java.lang.String  objectType ,)byte[]  objectZippedData )*
     */
    public java.lang.String uploadReportObject(java.lang.String reportObjectAbsolutePathURL,java.lang.String objectType,byte[] objectZippedData) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation uploadReportObject");
        System.out.println(reportObjectAbsolutePathURL);
        System.out.println(objectType);
        System.out.println(objectZippedData);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#updateReportDefinition(java.lang.String  reportAbsPath ,)com.ws.stub.ReportDefinition  newReportDefn )*
     */
    public boolean updateReportDefinition(java.lang.String reportAbsPath,com.ws.stub.ReportDefinition newReportDefn) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation updateReportDefinition");
        System.out.println(reportAbsPath);
        System.out.println(newReportDefn);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#isFolderExist(java.lang.String  folderAbsolutePath )*
     */
    public boolean isFolderExist(java.lang.String folderAbsolutePath) throws AccessDeniedException_Exception    { 
        LOG.info("Executing operation isFolderExist");
        System.out.println(folderAbsolutePath);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#getSecurityModel(*
     */
    public java.lang.String getSecurityModel() { 
        LOG.info("Executing operation getSecurityModel");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#getReportParameters(com.ws.stub.ReportRequest  reportRequest )*
     */
    public com.ws.stub.ParamNameValues getReportParameters(com.ws.stub.ReportRequest reportRequest) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation getReportParameters");
        System.out.println(reportRequest);
        try {
            com.ws.stub.ParamNameValues _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#uploadTemplateForReport(java.lang.String  reportAbsolutePath ,)java.lang.String  templateName ,)java.lang.String  templateType ,)java.lang.String  locale ,)byte[]  templateData )*
     */
    public boolean uploadTemplateForReport(java.lang.String reportAbsolutePath,java.lang.String templateName,java.lang.String templateType,java.lang.String locale,byte[] templateData) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation uploadTemplateForReport");
        System.out.println(reportAbsolutePath);
        System.out.println(templateName);
        System.out.println(templateType);
        System.out.println(locale);
        System.out.println(templateData);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#hasReportAccess(java.lang.String  reportAbsolutePath )*
     */
    public boolean hasReportAccess(java.lang.String reportAbsolutePath) throws InvalidParametersException_Exception    { 
        LOG.info("Executing operation hasReportAccess");
        System.out.println(reportAbsolutePath);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#getXDOSchema(java.lang.String  reportAbsolutePath ,)java.lang.String  locale )*
     */
    public byte[] getXDOSchema(java.lang.String reportAbsolutePath,java.lang.String locale) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation getXDOSchema");
        System.out.println(reportAbsolutePath);
        System.out.println(locale);
        try {
            byte[] _return = new byte[0];
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#getBIPHTTPSessionInterval(*
     */
    public int getBIPHTTPSessionInterval() { 
        LOG.info("Executing operation getBIPHTTPSessionInterval");
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#createReportFolder(java.lang.String  folderAbsolutePath )*
     */
    public java.lang.String createReportFolder(java.lang.String folderAbsolutePath) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation createReportFolder");
        System.out.println(folderAbsolutePath);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#removeTemplateForReport(java.lang.String  reportAbsolutePath ,)java.lang.String  templateFileName )*
     */
    public boolean removeTemplateForReport(java.lang.String reportAbsolutePath,java.lang.String templateFileName) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation removeTemplateForReport");
        System.out.println(reportAbsolutePath);
        System.out.println(templateFileName);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#uploadReportDataChunk(java.lang.String  fileID ,)byte[]  reportDataChunk ,)java.lang.String  reportRawDataChunk )*
     */
    public java.lang.String uploadReportDataChunk(java.lang.String fileID,byte[] reportDataChunk,java.lang.String reportRawDataChunk) throws OperationFailedException_Exception    { 
        LOG.info("Executing operation uploadReportDataChunk");
        System.out.println(fileID);
        System.out.println(reportDataChunk);
        System.out.println(reportRawDataChunk);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#getTemplate(java.lang.String  reportAbsolutePath ,)java.lang.String  templateID ,)java.lang.String  locale )*
     */
    public byte[] getTemplate(java.lang.String reportAbsolutePath,java.lang.String templateID,java.lang.String locale) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation getTemplate");
        System.out.println(reportAbsolutePath);
        System.out.println(templateID);
        System.out.println(locale);
        try {
            byte[] _return = new byte[0];
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#runReport(com.ws.stub.ReportRequest  reportRequest ,)java.lang.String  appParams )*
     */
    public com.ws.stub.ReportResponse runReport(com.ws.stub.ReportRequest reportRequest,java.lang.String appParams) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation runReport");
        System.out.println(reportRequest);
        System.out.println(appParams);
        try {
            com.ws.stub.ReportResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#validateLogin(*
     */
    public boolean validateLogin() { 
        LOG.info("Executing operation validateLogin");
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#submitReport(byte[]  submitReportData ,)java.lang.String  appParams )*
     */
    public java.lang.String submitReport(byte[] submitReportData,java.lang.String appParams) throws AccessDeniedException_Exception , SchedulingException_Exception    { 
        LOG.info("Executing operation submitReport");
        System.out.println(submitReportData);
        System.out.println(appParams);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new SchedulingException_Exception("SchedulingException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#downloadReportDataChunk(java.lang.String  fileID ,)long  beginIdx ,)int  size )*
     */
    public com.ws.stub.ReportDataChunk downloadReportDataChunk(java.lang.String fileID,long beginIdx,int size) throws OperationFailedException_Exception    { 
        LOG.info("Executing operation downloadReportDataChunk");
        System.out.println(fileID);
        System.out.println(beginIdx);
        System.out.println(size);
        try {
            com.ws.stub.ReportDataChunk _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#getReportDefinition(java.lang.String  reportAbsolutePath )*
     */
    public com.ws.stub.ReportDefinition getReportDefinition(java.lang.String reportAbsolutePath) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation getReportDefinition");
        System.out.println(reportAbsolutePath);
        try {
            com.ws.stub.ReportDefinition _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#createReport(java.lang.String  reportName ,)java.lang.String  folderAbsolutePathURL ,)java.lang.String  templateFileName ,)byte[]  templateData ,)java.lang.String  xliffFileName ,)byte[]  xliffData ,)boolean  updateFlag )*
     */
    public java.lang.String createReport(java.lang.String reportName,java.lang.String folderAbsolutePathURL,java.lang.String templateFileName,byte[] templateData,java.lang.String xliffFileName,byte[] xliffData,boolean updateFlag) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation createReport");
        System.out.println(reportName);
        System.out.println(folderAbsolutePathURL);
        System.out.println(templateFileName);
        System.out.println(templateData);
        System.out.println(xliffFileName);
        System.out.println(xliffData);
        System.out.println(updateFlag);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#deleteReport(java.lang.String  reportAbsolutePath )*
     */
    public boolean deleteReport(java.lang.String reportAbsolutePath) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation deleteReport");
        System.out.println(reportAbsolutePath);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#getTemplateParameters(java.lang.String  reportAbsolutePath ,)java.lang.String  templateID )*
     */
    public java.util.List<com.ws.stub.ParamNameValue> getTemplateParameters(java.lang.String reportAbsolutePath,java.lang.String templateID) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation getTemplateParameters");
        System.out.println(reportAbsolutePath);
        System.out.println(templateID);
        try {
            java.util.List<com.ws.stub.ParamNameValue> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#getFolderContents(java.lang.String  folderAbsolutePath )*
     */
    public com.ws.stub.CatalogContents getFolderContents(java.lang.String folderAbsolutePath) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation getFolderContents");
        System.out.println(folderAbsolutePath);
        try {
            com.ws.stub.CatalogContents _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#getDeliveryServiceDefinition(*
     */
    public com.ws.stub.DeliveryServiceDefinition getDeliveryServiceDefinition() throws AccessDeniedException_Exception    { 
        LOG.info("Executing operation getDeliveryServiceDefinition");
        try {
            com.ws.stub.DeliveryServiceDefinition _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#isReportExist(java.lang.String  reportAbsolutePath )*
     */
    public boolean isReportExist(java.lang.String reportAbsolutePath) throws AccessDeniedException_Exception    { 
        LOG.info("Executing operation isReportExist");
        System.out.println(reportAbsolutePath);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#downloadReportObject(java.lang.String  reportAbsolutePath )*
     */
    public byte[] downloadReportObject(java.lang.String reportAbsolutePath) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation downloadReportObject");
        System.out.println(reportAbsolutePath);
        try {
            byte[] _return = new byte[0];
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#deleteFolder(java.lang.String  folderAbsolutePath )*
     */
    public boolean deleteFolder(java.lang.String folderAbsolutePath) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation deleteFolder");
        System.out.println(folderAbsolutePath);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

    /* (non-Javadoc)
     * @see com.ws.stub.ExternalReportWSSService#deliveryService(com.ws.stub.DeliveryRequest  deliveryRequest )*
     */
    public java.lang.String deliveryService(com.ws.stub.DeliveryRequest deliveryRequest) throws AccessDeniedException_Exception , InvalidParametersException_Exception , OperationFailedException_Exception    { 
        LOG.info("Executing operation deliveryService");
        System.out.println(deliveryRequest);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AccessDeniedException_Exception("AccessDeniedException...");
        //throw new InvalidParametersException_Exception("InvalidParametersException...");
        //throw new OperationFailedException_Exception("OperationFailedException...");
    }

}
