
package com.ws.stub;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-05-07T11:46:52.221+05:30
 * Generated source version: 2.7.18
 * 
 */
 
public class ExternalReportWSSService_ExternalReportWSSService_Server{

    protected ExternalReportWSSService_ExternalReportWSSService_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ExternalReportWSSServiceImpl();
        String address = "https://egzv-test.fs.em2.oraclecloud.com:443/xmlpserver/services/ExternalReportWSSService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ExternalReportWSSService_ExternalReportWSSService_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
