package com.ws.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-05-07T11:46:52.213+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", name = "ExternalReportWSSService")
@XmlSeeAlso({ObjectFactory.class})
public interface ExternalReportWSSService {

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateTemplateForReportRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateTemplateForReportResponse", fault = {})
    @RequestWrapper(localName = "updateTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.UpdateTemplateForReport")
    @ResponseWrapper(localName = "updateTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.UpdateTemplateForReportResponse")
    @WebResult(name = "updateTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public boolean updateTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsolutePath,
        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String templateName,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String locale,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] templateData
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportSampleDataRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportSampleDataResponse", fault = {})
    @RequestWrapper(localName = "getReportSampleData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetReportSampleData")
    @ResponseWrapper(localName = "getReportSampleDataResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetReportSampleDataResponse")
    @WebResult(name = "getReportSampleDataReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public byte[] getReportSampleData(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsolutePath
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadReportObjectRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadReportObjectResponse", fault = {})
    @RequestWrapper(localName = "uploadReportObject", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.UploadReportObject")
    @ResponseWrapper(localName = "uploadReportObjectResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.UploadReportObjectResponse")
    @WebResult(name = "uploadReportObjectReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public java.lang.String uploadReportObject(
        @WebParam(name = "reportObjectAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportObjectAbsolutePathURL,
        @WebParam(name = "objectType", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String objectType,
        @WebParam(name = "objectZippedData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] objectZippedData
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateReportDefinitionRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/updateReportDefinitionResponse", fault = {})
    @RequestWrapper(localName = "updateReportDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.UpdateReportDefinition")
    @ResponseWrapper(localName = "updateReportDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.UpdateReportDefinitionResponse")
    @WebResult(name = "updateReportDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public boolean updateReportDefinition(
        @WebParam(name = "reportAbsPath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsPath,
        @WebParam(name = "newReportDefn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        com.ws.stub.ReportDefinition newReportDefn
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/isFolderExistRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/isFolderExistResponse", fault = {})
    @RequestWrapper(localName = "isFolderExist", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.IsFolderExist")
    @ResponseWrapper(localName = "isFolderExistResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.IsFolderExistResponse")
    @WebResult(name = "isFolderExistReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public boolean isFolderExist(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String folderAbsolutePath
    ) throws AccessDeniedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getSecurityModelRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getSecurityModelResponse")
    @RequestWrapper(localName = "getSecurityModel", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetSecurityModel")
    @ResponseWrapper(localName = "getSecurityModelResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetSecurityModelResponse")
    @WebResult(name = "getSecurityModelReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public java.lang.String getSecurityModel();

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportParametersRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportParametersResponse", fault = {})
    @RequestWrapper(localName = "getReportParameters", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetReportParameters")
    @ResponseWrapper(localName = "getReportParametersResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetReportParametersResponse")
    @WebResult(name = "getReportParametersReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public com.ws.stub.ParamNameValues getReportParameters(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        com.ws.stub.ReportRequest reportRequest
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadTemplateForReportRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadTemplateForReportResponse", fault = {})
    @RequestWrapper(localName = "uploadTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.UploadTemplateForReport")
    @ResponseWrapper(localName = "uploadTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.UploadTemplateForReportResponse")
    @WebResult(name = "uploadTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public boolean uploadTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsolutePath,
        @WebParam(name = "templateName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String templateName,
        @WebParam(name = "templateType", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String templateType,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String locale,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] templateData
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/hasReportAccessRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/hasReportAccessResponse", fault = {})
    @RequestWrapper(localName = "hasReportAccess", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.HasReportAccess")
    @ResponseWrapper(localName = "hasReportAccessResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.HasReportAccessResponse")
    @WebResult(name = "hasReportAccessReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public boolean hasReportAccess(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsolutePath
    ) throws InvalidParametersException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getXDOSchemaRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getXDOSchemaResponse", fault = {})
    @RequestWrapper(localName = "getXDOSchema", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetXDOSchema")
    @ResponseWrapper(localName = "getXDOSchemaResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetXDOSchemaResponse")
    @WebResult(name = "getXDOSchemaReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public byte[] getXDOSchema(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsolutePath,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String locale
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getBIPHTTPSessionIntervalRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getBIPHTTPSessionIntervalResponse")
    @RequestWrapper(localName = "getBIPHTTPSessionInterval", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetBIPHTTPSessionInterval")
    @ResponseWrapper(localName = "getBIPHTTPSessionIntervalResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetBIPHTTPSessionIntervalResponse")
    @WebResult(name = "getBIPHTTPSessionIntervalReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public int getBIPHTTPSessionInterval();

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReportFolderRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReportFolderResponse", fault = {})
    @RequestWrapper(localName = "createReportFolder", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.CreateReportFolder")
    @ResponseWrapper(localName = "createReportFolderResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.CreateReportFolderResponse")
    @WebResult(name = "createReportFolderReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public java.lang.String createReportFolder(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String folderAbsolutePath
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/removeTemplateForReportRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/removeTemplateForReportResponse", fault = {})
    @RequestWrapper(localName = "removeTemplateForReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.RemoveTemplateForReport")
    @ResponseWrapper(localName = "removeTemplateForReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.RemoveTemplateForReportResponse")
    @WebResult(name = "removeTemplateForReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public boolean removeTemplateForReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsolutePath,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String templateFileName
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadReportDataChunkRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/uploadReportDataChunkResponse", fault = {})
    @RequestWrapper(localName = "uploadReportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.UploadReportDataChunk")
    @ResponseWrapper(localName = "uploadReportDataChunkResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.UploadReportDataChunkResponse")
    @WebResult(name = "uploadReportDataChunkReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public java.lang.String uploadReportDataChunk(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String fileID,
        @WebParam(name = "reportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] reportDataChunk,
        @WebParam(name = "reportRawDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportRawDataChunk
    ) throws OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplateRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplateResponse", fault = {})
    @RequestWrapper(localName = "getTemplate", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetTemplate")
    @ResponseWrapper(localName = "getTemplateResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetTemplateResponse")
    @WebResult(name = "getTemplateReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public byte[] getTemplate(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String templateID,
        @WebParam(name = "locale", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String locale
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/runReportRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/runReportResponse", fault = {})
    @RequestWrapper(localName = "runReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.RunReport")
    @ResponseWrapper(localName = "runReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.RunReportResponse")
    @WebResult(name = "runReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public com.ws.stub.ReportResponse runReport(
        @WebParam(name = "reportRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        com.ws.stub.ReportRequest reportRequest,
        @WebParam(name = "appParams", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String appParams
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/validateLoginRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/validateLoginResponse")
    @RequestWrapper(localName = "validateLogin", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.ValidateLogin")
    @ResponseWrapper(localName = "validateLoginResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.ValidateLoginResponse")
    @WebResult(name = "validateLoginReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public boolean validateLogin();

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/submitReportRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/PublicReportService/ExternalReportWSSService/submitReportResponse", fault = {})
    @RequestWrapper(localName = "submitReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.SubmitReport")
    @ResponseWrapper(localName = "submitReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.SubmitReportResponse")
    @WebResult(name = "submitReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public java.lang.String submitReport(
        @WebParam(name = "submitReportData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] submitReportData,
        @WebParam(name = "appParams", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String appParams
    ) throws AccessDeniedException_Exception, SchedulingException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/downloadReportDataChunkRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/downloadReportDataChunkResponse", fault = {})
    @RequestWrapper(localName = "downloadReportDataChunk", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.DownloadReportDataChunk")
    @ResponseWrapper(localName = "downloadReportDataChunkResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.DownloadReportDataChunkResponse")
    @WebResult(name = "downloadReportDataChunkReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public com.ws.stub.ReportDataChunk downloadReportDataChunk(
        @WebParam(name = "fileID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String fileID,
        @WebParam(name = "beginIdx", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        long beginIdx,
        @WebParam(name = "size", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        int size
    ) throws OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportDefinitionRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getReportDefinitionResponse", fault = {})
    @RequestWrapper(localName = "getReportDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetReportDefinition")
    @ResponseWrapper(localName = "getReportDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetReportDefinitionResponse")
    @WebResult(name = "getReportDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public com.ws.stub.ReportDefinition getReportDefinition(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsolutePath
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReportRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/createReportResponse", fault = {})
    @RequestWrapper(localName = "createReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.CreateReport")
    @ResponseWrapper(localName = "createReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.CreateReportResponse")
    @WebResult(name = "createReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public java.lang.String createReport(
        @WebParam(name = "reportName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportName,
        @WebParam(name = "folderAbsolutePathURL", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String folderAbsolutePathURL,
        @WebParam(name = "templateFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String templateFileName,
        @WebParam(name = "templateData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] templateData,
        @WebParam(name = "XLIFFFileName", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String xliffFileName,
        @WebParam(name = "XLIFFData", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        byte[] xliffData,
        @WebParam(name = "updateFlag", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        boolean updateFlag
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteReportRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteReportResponse", fault = {})
    @RequestWrapper(localName = "deleteReport", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.DeleteReport")
    @ResponseWrapper(localName = "deleteReportResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.DeleteReportResponse")
    @WebResult(name = "deleteReportReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public boolean deleteReport(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsolutePath
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplateParametersRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getTemplateParametersResponse", fault = {})
    @RequestWrapper(localName = "getTemplateParameters", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetTemplateParameters")
    @ResponseWrapper(localName = "getTemplateParametersResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetTemplateParametersResponse")
    @WebResult(name = "getTemplateParametersReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public java.util.List<com.ws.stub.ParamNameValue> getTemplateParameters(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsolutePath,
        @WebParam(name = "templateID", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String templateID
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getFolderContentsRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getFolderContentsResponse", fault = {})
    @RequestWrapper(localName = "getFolderContents", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetFolderContents")
    @ResponseWrapper(localName = "getFolderContentsResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetFolderContentsResponse")
    @WebResult(name = "getFolderContentsReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public com.ws.stub.CatalogContents getFolderContents(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String folderAbsolutePath
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getDeliveryServiceDefinitionRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/getDeliveryServiceDefinitionResponse", fault = {})
    @RequestWrapper(localName = "getDeliveryServiceDefinition", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetDeliveryServiceDefinition")
    @ResponseWrapper(localName = "getDeliveryServiceDefinitionResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.GetDeliveryServiceDefinitionResponse")
    @WebResult(name = "getDeliveryServiceDefinitionReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public com.ws.stub.DeliveryServiceDefinition getDeliveryServiceDefinition() throws AccessDeniedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/isReportExistRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/isReportExistResponse", fault = {})
    @RequestWrapper(localName = "isReportExist", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.IsReportExist")
    @ResponseWrapper(localName = "isReportExistResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.IsReportExistResponse")
    @WebResult(name = "isReportExistReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public boolean isReportExist(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsolutePath
    ) throws AccessDeniedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/downloadReportObjectRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/downloadReportObjectResponse", fault = {})
    @RequestWrapper(localName = "downloadReportObject", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.DownloadReportObject")
    @ResponseWrapper(localName = "downloadReportObjectResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.DownloadReportObjectResponse")
    @WebResult(name = "downloadReportObjectReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public byte[] downloadReportObject(
        @WebParam(name = "reportAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String reportAbsolutePath
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteFolderRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deleteFolderResponse", fault = {})
    @RequestWrapper(localName = "deleteFolder", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.DeleteFolder")
    @ResponseWrapper(localName = "deleteFolderResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.DeleteFolderResponse")
    @WebResult(name = "deleteFolderReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public boolean deleteFolder(
        @WebParam(name = "folderAbsolutePath", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        java.lang.String folderAbsolutePath
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;

    @WebMethod
    @Action(input = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deliveryServiceRequest", output = "http://xmlns.oracle.com/oxp/service/PublicReportService/ExternalReportWSSService/deliveryServiceResponse", fault = {})
    @RequestWrapper(localName = "deliveryService", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.DeliveryService")
    @ResponseWrapper(localName = "deliveryServiceResponse", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService", className = "com.ws.stub.DeliveryServiceResponse")
    @WebResult(name = "deliveryServiceReturn", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
    public java.lang.String deliveryService(
        @WebParam(name = "deliveryRequest", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
        com.ws.stub.DeliveryRequest deliveryRequest
    ) throws AccessDeniedException_Exception, InvalidParametersException_Exception, OperationFailedException_Exception;
}
