
package com.ws.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-05-07T11:46:52.195+05:30
 * Generated source version: 2.7.18
 */

@WebFault(name = "OperationFailedException", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
public class OperationFailedException_Exception extends Exception {
    
    private com.ws.stub.OperationFailedException operationFailedException;

    public OperationFailedException_Exception() {
        super();
    }
    
    public OperationFailedException_Exception(String message) {
        super(message);
    }
    
    public OperationFailedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public OperationFailedException_Exception(String message, com.ws.stub.OperationFailedException operationFailedException) {
        super(message);
        this.operationFailedException = operationFailedException;
    }

    public OperationFailedException_Exception(String message, com.ws.stub.OperationFailedException operationFailedException, Throwable cause) {
        super(message, cause);
        this.operationFailedException = operationFailedException;
    }

    public com.ws.stub.OperationFailedException getFaultInfo() {
        return this.operationFailedException;
    }
}
