
package com.ws.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-05-07T11:46:52.198+05:30
 * Generated source version: 2.7.18
 */

@WebFault(name = "SchedulingException", targetNamespace = "http://xmlns.oracle.com/oxp/service/PublicReportService")
public class SchedulingException_Exception extends Exception {
    
    private com.ws.stub.SchedulingException schedulingException;

    public SchedulingException_Exception() {
        super();
    }
    
    public SchedulingException_Exception(String message) {
        super(message);
    }
    
    public SchedulingException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SchedulingException_Exception(String message, com.ws.stub.SchedulingException schedulingException) {
        super(message);
        this.schedulingException = schedulingException;
    }

    public SchedulingException_Exception(String message, com.ws.stub.SchedulingException schedulingException, Throwable cause) {
        super(message, cause);
        this.schedulingException = schedulingException;
    }

    public com.ws.stub.SchedulingException getFaultInfo() {
        return this.schedulingException;
    }
}
